Repository DnJ0408/saram-byeol, pull requests merged in 2025-04, with the labels that each got.

#8 Feature/#3 contact list
  pnpm-lock.yaml
  src/app/(pages)/people/page.tsx
  src/app/api/.gitkeep
  src/app/api/supabase/client.ts
  src/app/api/supabase/service.ts
  src/app/layout.tsx
  src/app/providers.tsx
  src/components/contacts/ContactItem.tsx
  src/components/contacts/ContactList.tsx
  src/types/.gitkeep
  src/types/contacts.ts
Labels: 🦁영진, ♻️ Refactor, ✨ Feature, 📬 API

#11 Feature/#5 calendar page
  package.json
  pnpm-lock.yaml
  src/app/(pages)/calander/page.tsx
  src/app/(pages)/calendar/page.tsx
  src/app/api/supabase/client.ts
  src/app/api/supabase/service.ts
  src/components/commons/.gitkeep
  src/components/commons/MainCalendar.tsx
  src/constants/queryKey.ts
  src/hooks/.gitkeep
  src/hooks/useGetCalendarPlans.ts
  src/types/plans.ts
Labels: 🍀진채, ✨ Feature, 📬 API

#9 Feature/#6 login signup page
  src/app/(pages)/signIn/page.tsx
  src/app/(pages)/signUp/page.tsx
  src/app/api/supabase/service.ts
  src/constants/paths.ts
  src/constants/placeholders.ts
  src/store/zustand/store.ts
Labels: 🐸종연, ✨ Feature, 📬 API

#14 Style/#10 contact list
  package.json
  pnpm-lock.yaml
  src/app/(pages)/people/page.tsx
  src/components/contacts/ContactItem.tsx
  src/components/contacts/ContactList.tsx
Labels: 🦁영진, 🎨 Style

#19 Feature/#13 make plans function
  package.json
  pnpm-lock.yaml
  src/app/api/supabase/service.ts
  src/app/page.tsx
  src/components/commons/MainCalendar.tsx
  src/components/plans/ContactsField.tsx
  src/components/plans/DateInputField.tsx
  src/components/plans/DetailField.tsx
  src/components/plans/PlanForm.tsx
  src/components/plans/TitleField.tsx
  src/components/ui/calendar.tsx
  src/components/ui/command.tsx
  src/components/ui/dialog.tsx
  src/components/ui/input.tsx
  src/components/ui/popover.tsx
  src/components/ui/textarea.tsx
  src/constants/queryKey.ts
  src/hooks/mutations/useMutateInsertNewPlan.ts
  src/hooks/queries/useGetCalendarPlans.ts
  src/hooks/queries/useGetContactsByUserID.ts
  src/lib/planFormUtils.ts
  src/lib/schemas/plansSchema.ts
  src/types/plans.ts
Labels: 🧓기리, ✨ Feature

#20 Feature/#18 signin signup validation
  src/app/(pages)/signIn/page.tsx
  src/app/(pages)/signUp/page.tsx
  src/app/api/supabase/service.ts
  src/constants/paths.ts
  src/constants/placeholders.ts
  src/lib/schemas/signinSchema.ts
  src/lib/schemas/signupSchema.ts
  src/store/zustand/store.ts
Labels: 🐸종연, ✨ Feature

#25 Feature/#15 add person profile
  package.json
  src/app/(pages)/people/page.tsx
  src/app/api/supabase/service.ts
  src/app/layout.tsx
  src/components/contacts/ContactItem.tsx
  src/components/contacts/ContactList.tsx
  src/components/contacts/SideSheet.tsx
  src/components/contacts/addContactForm/ContactFormSubmitButton.tsx
  src/components/contacts/addContactForm/ContactTextField.tsx
  src/components/contacts/addContactForm/Index.tsx
  src/components/contacts/addContactForm/ProfileImageUpload.tsx
  src/components/contacts/addContactForm/RelationshipSelector.tsx
  src/components/ui/dropdown-menu.tsx
  src/hooks/useContactForm.ts
  src/lib/schemas/contactFormSchema.ts
Labels: 🦁영진, ♻️ Refactor, ✨ Feature, 🎨 Style

#23 Style/#17 people detail
  pnpm-lock.yaml
  src/app/(pages)/people/page.tsx
  src/components/contacts/ContactList.tsx
  src/components/contacts/ContactPlans.tsx
  src/components/contacts/ContactProfile.tsx
  src/components/contacts/PeopleDetailPanel.tsx
Labels: 🦄시헌, 🎨 Style

#31 Feature/#27 pinned contacts
  pnpm-lock.yaml
  src/app/api/supabase/service.ts
  src/components/contacts/ContactItem.tsx
  src/components/contacts/ContactList.tsx
  src/types/contacts.ts
Labels: 🦁영진, ✨ Feature, 🎨 Style, 📬 API

#32 Refactor/#26 calendar
  src/app/api/supabase/service.ts
  src/app/globals.css
  src/components/calendar/AddPlans.tsx
  src/components/calendar/CalendarPopOver.tsx
  src/components/calendar/CustomToolbar.tsx
  src/components/calendar/MainCalendar.tsx
  src/components/calendar/UpcomingPlans.tsx
  src/constants/queryKey.ts
  src/hooks/mutations/useMutateInsertNewPlan.ts
  src/hooks/mutations/useUpadateEventMutate.ts
  src/hooks/queries/useGetCalendarPlans.ts
Labels: 🍀진채, ✨ Feature, 📬 API

#30 22 feature 약속에 장소정보 추가
  package.json
  src/app/api/planForm/search/route.ts
  src/app/api/planForm/search/service.ts
  src/components/plans/PlaceField.tsx
  src/components/plans/PlanForm.tsx
  src/components/ui/select.tsx
  src/constants/env.constant.ts
  src/lib/planFormUtils.ts
  src/lib/schemas/plansSchema.ts
  src/types/plans.ts
Labels: 🧓기리, ✨ Feature, 📬 API

#35 Feature/#28 social login
  src/app/(pages)/people/page.tsx
  src/app/(pages)/signIn/page.tsx
  src/app/(pages)/signUp/page.tsx
  src/app/api/supabase/service.ts
  src/store/zustand/store.ts
Labels: 🐸종연, ✨ Feature, 📬 API

#37 Feature/#34 popover colors
  src/app/api/supabase/service.ts
  src/app/globals.css
  src/components/calendar/CalendarPopOver.tsx
  src/components/calendar/ColorOptions.tsx
  src/components/calendar/MainCalendar.tsx
  src/constants/supabaseTable.ts
  src/hooks/queries/useGetCalendarPlans.ts
  src/lib/utils/calendarStyle.ts
  src/types/plans.ts
Labels: 🍀진채, ✨ Feature, 🎨 Style

#33 Feature/#24 people detail
  src/app/(pages)/people/page.tsx
  src/app/api/supabase/service.ts
  src/components/contactDetail/ContactPlans.tsx
  src/components/contactDetail/ContactPlansCard.tsx
  src/components/contactDetail/ContactProfile.tsx
  src/components/contactDetail/PeopleDetailPanel.tsx
  src/components/contactDetail/editContactForm/ContactForm.tsx
  src/components/contactDetail/editContactForm/EditContactForm.tsx
  src/components/contactDetail/editContactForm/EditContactFormSubmitButton.tsx
  src/components/contactDetail/editContactForm/EditProfileImageUpload.tsx
  src/components/contacts/ContactPlans.tsx
  src/components/contacts/SideSheet.tsx
  src/hooks/mutations/useMutateEditContact.ts
Labels: 🦄시헌, ✨ Feature, 📬 API

#41 Feat/#40 feature navigation bar layout
  next.config.mjs
  src/app/(pages)/(nav)/calendar/page.tsx
  src/app/(pages)/(nav)/layout.tsx
  src/app/(pages)/(nav)/people/page.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/components/contacts/ContactList.tsx
  src/components/nav/LeftNavBar.tsx
  src/components/plans/PlaceField.tsx
  src/lib/planFormUtils.ts
  tailwind.config.ts
Labels: 🧓기리, ♻️ Refactor, ✨ Feature, 🎨 Style

#45 Style/#39 signin signup page styling
  public/google_login_img.png
  public/kakao_login_img.png
  public/saram-byeol_img.avif
  src/app/(pages)/signIn/page.tsx
  src/app/(pages)/signUp/page.tsx
  src/constants/placeholders.ts
  src/store/zustand/store.ts
Labels: 🐸종연, 🎨 Style

#43 Feature/#38 popover close position
  src/app/globals.css
  src/components/calendar/CalendarPopOver.tsx
  src/components/calendar/ColorOptions.tsx
Labels: 🍀진채, ✨ Feature, 🎨 Style

#47 fix#46 PlanForm에서 날짜 저장시 string값 및 시간 값 조정
  src/components/plans/PlanForm.tsx
  src/lib/planFormUtils.ts
  src/types/plans.ts
Labels: 🧓기리, ✨ Feature

#48 Feature/#42 edit people plan
  pnpm-lock.yaml
  src/app/api/supabase/service.ts
  src/components/contactDetail/ContactPlans.tsx
  src/components/contactDetail/ContactPlansCard.tsx
  src/components/contactDetail/editPlanForm/EditPlanForm.tsx
  src/hooks/mutations/useMutateUpdatePlan.ts
  src/types/plans.ts
Labels: 🦄시헌, ✨ Feature, 📬 API

#54 Feature/#44 toolbar UI
  src/app/(pages)/(nav)/calendar/page.tsx
  src/app/api/holidays/route.ts
  src/components/calendar/AddPlanButton.tsx
  src/components/calendar/AddPlans.tsx
  src/components/calendar/ColorOptions.tsx
  src/components/calendar/CustomToolbar.tsx
  src/components/calendar/MoveMonthButton.tsx
  src/components/calendar/UpcomingPlanButton.tsx
  src/components/calendar/UpcomingPlans.tsx
  src/constants/env.constant.ts
Labels: 🍀진채, 🎨 Style

#55 Feature/#36 upcoming plan list
  src/app/(pages)/(nav)/calendar/page.tsx
  src/app/api/supabase/service.ts
  src/components/calendar/CustomToolbar.tsx
  src/components/schedule/UpcomingPlanCard.tsx
  src/components/schedule/UpcomingPlans.tsx
  src/lib/utils/dateUtils.ts
Labels: 🦁영진, ♻️ Refactor, ✨ Feature, 🎨 Style

#57 Refactor/#53 delete locales
  src/components/calendar/MainCalendar.tsx
  src/lib/planFormUtils.ts
Labels: 🍀진채, 📬 API

#62 Style#46 style apply style to function add new plan
  src/app/fonts/LICENSE.txt
  src/app/fonts/pretendard/PretendardVariable.woff2
  src/app/layout.tsx
  src/app/page.tsx
  src/components/calendar/ColorOptions.tsx
  src/components/plans/ContactsField.tsx
  src/components/plans/DateInputField.tsx
  src/components/plans/DetailField.tsx
  src/components/plans/PlaceField.tsx
  src/components/plans/PlanForm.tsx
  src/components/plans/PriorityField.tsx
  src/components/plans/TitleField.tsx
  src/lib/planFormUtils.ts
  src/lib/schemas/plansSchema.ts
  src/types/plans.ts
  tailwind.config.ts
Labels: 🧓기리, 🎨 Style, 🐞 BugFix

#63 Refactor/#56 signin signup refactoring
  public/google_login_img.png
  public/kakao_login_img.png
  src/app/(pages)/signIn/page.tsx
  src/app/(pages)/signUp/page.tsx
  src/components/calendar/CustomToolbar.tsx
  src/components/schedule/UpcomingPlans.tsx
  src/components/signin/SigninForm.tsx
  src/components/signin/SigninSocial.tsx
  src/components/signup/SignupForm.tsx
  src/constants/paths.ts
  src/constants/placeholders.ts
  src/hooks/useSignin.ts
  src/hooks/useSignup.ts
  src/lib/schemas/signupSchema.ts
  src/store/zustand/store.ts
Labels: 🐸종연, ♻️ Refactor

#70 Bugfix#69 로그아웃 핸들러에서 (event === 'SIGNED_OUT')일때 적용되던 로그아웃 함수를 제거
  src/components/nav/LeftNavBar.tsx
  src/store/zustand/store.ts
Labels: 🧓기리

#68 Refactor/#61 calendar sign in
  src/app/(pages)/(nav)/calendar/layout.tsx
  src/app/(pages)/(nav)/calendar/page.tsx
  src/app/api/supabase/service.ts
  src/components/calendar/AddPlanButton.tsx
  src/components/calendar/CalendarPopOver.tsx
  src/components/calendar/MainCalendar.tsx
  src/components/calendar/popOver/CalendarPopOver.tsx
  src/components/calendar/popOver/ColorOptions.tsx
  src/components/calendar/popOver/PopOverForm.tsx
  src/types/plans.ts
Labels: 🍀진채, ♻️ Refactor, 📃 Docs

#65 Feature/#49 del people detail
  src/app/api/supabase/service.ts
  src/components/contactDetail/ContactPlans.tsx
  src/components/contactDetail/ContactPlansCard.tsx
  src/components/contactDetail/ContactProfile.tsx
  src/components/contactDetail/PeopleDetailPanel.tsx
  src/components/contactDetail/editContactForm/EditContactForm.tsx
  src/components/contactDetail/editPlanForm/EditPlanForm.tsx
  src/components/toast/ConfirmToast.tsx
  src/constants/queryKey.ts
  src/hooks/mutations/useMutateDeleteContact.ts
  src/hooks/mutations/useMutateDeletePlan.ts
Labels: 🦄시헌, ✨ Feature, 📬 API

#72 Refactor/#71 사용자에 따른 약속 데이터 가져오기
  src/app/api/supabase/service.ts
Labels: 🍀진채, ♻️ Refactor, 📬 API

#73 Style/#58 popover UI
  src/components/calendar/popOver/CalendarPopOver.tsx
  src/components/calendar/popOver/ColorOptions.tsx
  src/components/calendar/popOver/PopOverForm.tsx
Labels: 🍀진채, 🎨 Style

#77 Feature/#74 calendar connection
  src/app/(pages)/(nav)/calendar/page.tsx
  src/app/api/supabase/service.ts
  src/components/calendar/MainCalendar.tsx
  src/components/calendar/SelectPlan.tsx
  src/components/plans/PlanForm.tsx
  src/types/plans.ts
Labels: 🍀진채, ✨ Feature

#82 Style/#75 upcoming plan card color
  src/components/plans/PlanForm.tsx
  src/components/schedule/UpcomingPlanCard.tsx
  src/components/schedule/UpcomingPlans.tsx
Labels: 🦁영진, 🎨 Style

#81 Feature/#78 toolbar buttons
  src/app/(pages)/(nav)/calendar/page.tsx
  src/components/calendar/AddPlanButton.tsx
  src/components/calendar/CustomToolbar.tsx
  src/components/calendar/MainCalendar.tsx
  src/components/calendar/UpcomingPlanButton.tsx
  src/components/plans/PlanForm.tsx
Labels: 🍀진채, ✨ Feature

#80 Feature/#79 people logout redirect
  src/app/(pages)/(nav)/people/page.tsx
Labels: 🐸종연, ✨ Feature

#86 Bugfix 약속 상세 날짜 출력 수정
  src/app/(pages)/(nav)/calendar/page.tsx
  src/components/calendar/SelectPlan.tsx
Labels: 🍀진채, 🐞 BugFix

#90 Fix/#88 사용자 프로필 이름 표시 로직 수정
  public/favicon.ico
  public/favicon.png
  public/og-image.png
  src/app/favicon.ico
  src/app/layout.tsx
  src/components/nav/LeftNavBar.tsx
Labels: 🧓기리, 🐞 BugFix

#91 fix:#89 구글 및 카카오 로그인 리다이렉트 URL을 로컬에서 배포된 URL로 변경
  src/app/api/supabase/service.ts
Labels: 🐸종연, 🐞 BugFix

#93 Refactor/#92 onauthstatechange to root
  src/app/(pages)/(nav)/people/page.tsx
  src/app/api/supabase/service.ts
  src/app/layout.tsx
  src/components/onauthstatechange/OnAuthStateChange.tsx
  src/constants/redirecturl.ts
  src/hooks/useSignin.ts
Labels: 🐸종연, ♻️ Refactor

#94 Feature/#83 plans detail button
  src/components/calendar/SelectPlan.tsx
  src/constants/queryKey.ts
  src/hooks/mutations/useMutateDeleteSelectPlan.ts
  src/hooks/queries/useGetSelectPlan.ts
Labels: 🍀진채, ✨ Feature, 🎨 Style

#97 Feature/#95 popover buttons
  src/app/(pages)/(nav)/calendar/page.tsx
  src/components/calendar/MainCalendar.tsx
  src/components/calendar/SelectPlan.tsx
  src/components/calendar/popOver/CalendarPopOver.tsx
  src/components/calendar/popOver/PopOverForm.tsx
  src/components/plans/PlanForm.tsx
  src/lib/schemas/plansSchema.ts
  src/store/zustand/usePlanFormStore.ts
Labels: 🍀진채, ✨ Feature

#99 Style/#76 people detail
  src/app/api/supabase/service.ts
  src/components/contactDetail/ContactPlans.tsx
  src/components/contactDetail/ContactPlansCard.tsx
  src/components/contactDetail/ContactProfile.tsx
  src/components/contactDetail/editPlanForm/EditPlanForm.tsx
  src/types/contacts.ts
Labels: 🦄시헌, 🎨 Style

#101 Feature/#100 pinned contacts click event
  src/components/contacts/ContactItem.tsx
  src/components/contacts/ContactList.tsx
  src/components/contacts/SideSheet.tsx
  src/components/contacts/addContactForm/ContactFormSubmitButton.tsx
  src/components/contacts/addContactForm/ContactTextField.tsx
  src/components/contacts/addContactForm/Index.tsx
  src/components/contacts/addContactForm/ProfileImageUpload.tsx
  src/components/contacts/addContactForm/RelationshipSelector.tsx
  src/components/schedule/UpcomingPlanCard.tsx
  src/components/schedule/UpcomingPlans.tsx
Labels: 🦁영진, ✨ Feature

#114 Bugfix/#102 social login redirect error
  src/app/api/supabase/service.ts
  src/app/auth/callback/page.tsx
  src/components/signin/SigninSocial.tsx
  src/constants/redirecturl.ts
  src/store/zustand/store.ts
Labels: 🐸종연, 🐞 BugFix

#120 Bugfix/#104 sign in user plans
  src/app/(pages)/(nav)/calendar/page.tsx
  src/app/api/supabase/service.ts
  src/components/calendar/MainCalendar.tsx
  src/hooks/queries/useGetCalendarPlans.ts
Labels: 🍀진채, 🐞 BugFix

#113 Feature/#109 upcoming plans length
  src/app/(pages)/(nav)/calendar/page.tsx
  src/components/calendar/UpcomingPlanButton.tsx
Labels: 🍀진채, ✨ Feature, 🎨 Style

#116 Feature/#111 people plan detail
  src/app/(pages)/(nav)/people/page.tsx
  src/components/contactDetail/ContactPlans.tsx
  src/components/contactDetail/ContactPlansCard.tsx
  src/components/contactDetail/ContactProfile.tsx
  src/components/contactDetail/PeopleDetailPanel.tsx
  src/components/contactDetail/editContactForm/ContactForm.tsx
  src/components/contactDetail/editContactForm/EditContactForm.tsx
  src/components/contactDetail/editContactForm/EditContactFormSubmitButton.tsx
  src/components/contactDetail/editContactForm/EditProfileImageUpload.tsx
  src/components/contactDetail/editPlanForm/EditPlanForm.tsx
  src/hooks/mutations/useMutateInsertNewPlan.ts
  src/hooks/mutations/useMutateUpdatePlan.ts
Labels: 🦄시헌, ✨ Feature, 🎨 Style

#121 Bugfix/#118 calendar plans detail error
  src/app/(pages)/(nav)/calendar/page.tsx
  src/components/calendar/MainCalendar.tsx
  src/components/contactDetail/editPlanForm/EditPlanForm.tsx
  src/types/plans.ts
Labels: 🍀진채, 🐞 BugFix

#128 Bugfix/#123 calendar errors
  src/app/(pages)/(nav)/calendar/page.tsx
  src/app/api/supabase/service.ts
  src/components/calendar/AddPlanButton.tsx
  src/components/calendar/CustomToolbar.tsx
  src/components/calendar/SelectPlan.tsx
  src/components/calendar/UpcomingPlanButton.tsx
  src/components/contactDetail/ContactPlans.tsx
  src/components/contactDetail/editPlanForm/EditPlanForm.tsx
  src/hooks/mutations/useMutateInsertNewPlan.ts
  src/hooks/mutations/useUpadateEventMutate.ts
  src/types/plans.ts
Labels: 🍀진채, 🐞 BugFix

#129 Style/#110 people detail
  src/components/contactDetail/ContactProfile.tsx
Labels: 🦄시헌, 🎨 Style

#124 Feature/#112 add contact form enhance
  src/components/contacts/ContactList.tsx
  src/components/contacts/SideSheet.tsx
  src/components/contacts/addContactForm/AddContactForm.tsx
  src/components/contacts/addContactForm/ContactTextField.tsx
  src/hooks/mutations/useMutateEditContact.ts
  src/hooks/useContactForm.ts
  src/lib/schemas/contactFormSchema.ts
  src/types/contacts.ts
Labels: 🦁영진, ✨ Feature, 🐞 BugFix

#130 Style/#125 add contact form with side sheet
  src/components/contactDetail/editContactForm/ContactForm.tsx
  src/components/contacts/ContactItem.tsx
  src/components/contacts/ContactList.tsx
  src/components/contacts/SideSheet.tsx
  src/components/contacts/addContactForm/AddContactForm.tsx
  src/components/contacts/addContactForm/ContactMemoField.tsx
  src/components/contacts/addContactForm/ContactTextField.tsx
  src/components/contacts/addContactForm/RelationshipSelector.tsx
  src/hooks/mutations/useMutateEditContact.ts
  src/hooks/useContactForm.ts
  src/lib/schemas/contactFormSchema.ts
Labels: 🦁영진, 🎨 Style

#133 Bugfix/#131 popover more error
  src/app/(pages)/(nav)/calendar/page.tsx
  src/components/plans/PlanForm.tsx
Labels: 🍀진채, 🐞 BugFix

#138 Feature/#134 image edit delete in side sheet
  src/components/contacts/addContactForm/AddContactForm.tsx
  src/components/contacts/addContactForm/ContactFormCancelButton.tsx
  src/components/contacts/addContactForm/ContactFormSubmitButton.tsx
  src/components/contacts/addContactForm/ContactTextField.tsx
  src/components/contacts/addContactForm/ProfileImageUpload.tsx
  src/lib/schemas/contactFormSchema.ts
Labels: 🦁영진, ✨ Feature, 🎨 Style

#137 Feat/#117 demo service
  public/app-logo.png
  public/default_profile.png
  src/app/(pages)/(nav)/calendar/page.tsx
  src/app/(pages)/(nav)/people/page.tsx
  src/components/calendar/SelectPlan.tsx
  src/components/calendar/popOver/PopOverForm.tsx
  src/components/contactDetail/ContactPlans.tsx
  src/components/contactDetail/ContactPlansCard.tsx
  src/components/contactDetail/ContactProfile.tsx
  src/components/contactDetail/PeopleDetailPanel.tsx
  src/components/contactDetail/editPlanForm/EditPlanForm.tsx
  src/components/contacts/ContactItem.tsx
  src/components/contacts/ContactList.tsx
  src/components/home/MainDoor.tsx
  src/components/nav/LeftNavBar.tsx
  src/components/plans/ContactsField.tsx
  src/components/plans/PlanForm.tsx
  src/components/plans/TitleField.tsx
  src/components/schedule/UpcomingPlans.tsx
  src/constants/demoData.ts
  src/constants/placeholders.ts
  src/hooks/mutations/useMutateEditContact.ts
  src/hooks/queries/useGetCalendarPlans.ts
  src/lib/schemas/plansSchema.ts
  src/store/zustand/store.ts
  src/store/zustand/useDemoStore.ts
Labels: 🧓기리, ✨ Feature, 🎨 Style, 🐞 BugFix

#139 Style/#136 signin signup responsive design
  src/app/(pages)/signIn/page.tsx
  src/app/(pages)/signUp/page.tsx
  src/components/signin/SigninForm.tsx
  src/components/signin/SigninSocial.tsx
  src/components/signup/SignupForm.tsx
Labels: 🐸종연, 🎨 Style

#145 Fix/#135 people detail
  src/app/(pages)/(nav)/people/page.tsx
  src/components/contactDetail/ContactProfile.tsx
  src/components/contactDetail/PeopleDetailPanel.tsx
  src/components/contactDetail/editContactForm/ContactForm.tsx
  src/components/contactDetail/editContactForm/EditContactForm.tsx
Labels: 🦄시헌, 🐞 BugFix

#144 Bugfix/#132 page transition error
  src/app/(pages)/(nav)/calendar/page.tsx
  src/components/calendar/SelectPlan.tsx
  src/hooks/mutations/useMutateDeletePlan.ts
  src/hooks/mutations/useMutateDeleteSelectPlan.ts
  src/hooks/mutations/useMutateUpdatePlan.ts
Labels: 🍀진채, 🐞 BugFix

#148 Feature/#122 toolbar button dynamic UI
  src/app/(pages)/(nav)/calendar/page.tsx
  src/components/calendar/AddPlanButton.tsx
  src/components/calendar/CustomToolbar.tsx
  src/components/calendar/MainCalendar.tsx
  src/components/calendar/UpcomingPlanButton.tsx
Labels: 🍀진채, ✨ Feature, 🎨 Style

#146 Feature/#87 contact list infinite scroll
  src/app/api/supabase/service.ts
  src/components/contacts/ContactList.tsx
  src/constants/queryKey.ts
  src/hooks/mutations/useMutateTogglePinContact.ts
  src/hooks/queries/useGetContactsForInfinite.ts
  src/hooks/useContactForm.ts
  src/types/contacts.ts
Labels: 🦁영진, ✨ Feature

#151 Style/#147 selected contact list
  src/app/(pages)/(nav)/people/page.tsx
  src/components/contacts/ContactItem.tsx
  src/components/contacts/ContactList.tsx
  src/hooks/mutations/useMutateInfiniteContact.ts
Labels: 🦁영진, ✨ Feature, 🎨 Style

#150 Featurue/#149 red days
  src/app/(pages)/(nav)/calendar/page.tsx
  src/components/calendar/CustomDateHeader.tsx
  src/components/calendar/MainCalendar.tsx
Labels: 🍀진채, ✨ Feature, 🎨 Style

#154 Feature/#153 loading spinner
  src/app/(pages)/(nav)/calendar/page.tsx
  src/components/Loading.tsx
  src/components/contacts/ContactList.tsx
Labels: 🍀진채, ✨ Feature, 🎨 Style

#158 Feat/#143 landing page
  public/fonts/gmarket/GmarketSansBold.woff2
  public/fonts/gmarket/GmarketSansLight.woff2
  public/fonts/gmarket/GmarketSansMedium.woff2
  public/fonts/pretendard/LICENSE.txt
  public/fonts/pretendard/PretendardVariable.woff2
  public/home/app-logo-icon-noShadow.png
  public/home/app-logo-icon.png
  public/home/landing-calendar.png
  public/home/landing-mockup.png
  public/home/landing-people.png
  public/nav/app-logo-greyscale.png
  public/nav/app-logo.png
  public/nav/default_profile.png
  src/app/fonts/GeistMonoVF.woff
  src/app/fonts/GeistVF.woff
  src/app/fonts/gmarket.ts
  src/app/fonts/pretendard.ts
  src/app/layout.tsx
  src/app/page.tsx
  src/components/home/LandingPage.tsx
  src/components/home/MainDoor.tsx
  src/components/home/MainHeader.tsx
  src/components/home/SectionOne.tsx
  src/components/home/SectionThree.tsx
  src/components/home/SectionThreeEmail.tsx
  src/components/home/SectionTwo.tsx
  src/components/home/SectionTwoToggle.tsx
  src/components/nav/LeftNavBar.tsx
  src/constants/placeholders.ts
  src/hooks/useWheel.ts
  tailwind.config.ts
Labels: 🧓기리, ✨ Feature, 🎨 Style

#161 Style/#155 overlay in sidesheet
  src/components/contacts/ContactItem.tsx
  src/components/contacts/ContactList.tsx
  src/components/contacts/SideSheet.tsx
  src/components/contacts/addContactForm/ContactTextField.tsx
  src/components/contacts/addContactForm/ProfileImageUpload.tsx
  src/components/schedule/UpcomingPlanCard.tsx
  src/components/schedule/UpcomingPlans.tsx
Labels: 🦁영진, 🎨 Style

#164 Feat/#117 demo service (캘린더페이지 적용)
  src/app/(pages)/(nav)/calendar/page.tsx
  src/components/calendar/UpcomingPlanButton.tsx
  src/components/calendar/popOver/PopOverForm.tsx
  src/components/contactDetail/PeopleDetailPanel.tsx
  src/components/schedule/UpcomingPlans.tsx
  src/constants/demoData.ts
  src/hooks/queries/useGetCalendarPlans.ts
  src/hooks/queries/useGetDemoPlans.ts
  src/hooks/queries/useGetSelectPlan.ts
  src/store/zustand/useDemoStore.ts
Labels: 🧓기리, ♻️ Refactor, ✨ Feature

#165 Feature/#156 error component
  src/app/(pages)/(nav)/calendar/error.tsx
  src/app/(pages)/(nav)/calendar/page.tsx
  src/app/api/holidays/route.ts
  src/app/api/supabase/service.ts
  src/components/Error.tsx
  src/components/calendar/UpcomingPlanButton.tsx
  src/hooks/mutations/useUpadateEventMutate.ts
  src/hooks/queries/useGetHolidays.ts
Labels: 🍀진채, ✨ Feature, 📬 API

#163 Style/#152 people detail cd
  src/components/contactDetail/ContactPlans.tsx
  src/components/contactDetail/ContactProfile.tsx
  src/components/contactDetail/PeopleDetailPanel.tsx
  src/lib/utils/sortPlansByDate.ts
Labels: 🦄시헌, ✨ Feature, 🎨 Style

#171 Feature/#166 contacts edit mode
  src/app/api/supabase/service.ts
  src/components/contactDetail/ContactProfile.tsx
  src/components/contactDetail/PeopleDetailPanel.tsx
  src/components/contacts/ContactItem.tsx
  src/components/contacts/ContactList.tsx
  src/constants/queryKey.ts
  src/hooks/mutations/useMutateDeleteContact.ts
  src/hooks/mutations/useMutateDeleteContacts.ts
  src/hooks/mutations/useMutateInfiniteContact.ts
  src/hooks/queries/useGetContactsForInfinite.ts
  src/hooks/useContactForm.ts
Labels: 🦁영진, ✨ Feature

#173 Bugfix/#169 upcoming button blink
  src/app/(pages)/(nav)/calendar/page.tsx
  src/app/api/supabase/service.ts
  src/components/calendar/UpcomingPlanButton.tsx
  src/components/contactDetail/PeopleDetailPanel.tsx
  src/components/schedule/UpcomingPlans.tsx
  src/constants/queryKey.ts
  src/hooks/mutations/useMutateDeletePlan.ts
  src/hooks/mutations/useMutateDeleteSelectPlan.ts
  src/hooks/mutations/useMutateInsertNewPlan.ts
  src/hooks/mutations/useUpadateEventMutate.ts
  src/hooks/queries/useSetUpcomingCount.ts
Labels: 🍀진채, 🐞 BugFix

#175 Feature/#160 resetting a password
  src/app/(pages)/change-password/page.tsx
  src/app/(pages)/confirm-email/page.tsx
  src/app/(pages)/finish-signup/page.tsx
  src/app/(pages)/forgot-password/page.tsx
  src/app/(pages)/wait-change-password/page.tsx
  src/app/api/supabase/service.ts
  src/components/contacts/ContactList.tsx
  src/components/signin/SigninForm.tsx
  src/components/signup/SignupForm.tsx
  src/constants/paths.ts
  src/constants/placeholders.ts
  src/constants/redirecturl.ts
  src/hooks/useSignup.ts
  src/lib/schemas/changePasswordSchema.ts
  src/lib/schemas/sendEmailSchema.ts
  src/lib/schemas/signupSchema.ts
Labels: 🐸종연, ✨ Feature

#178 Style/#172 contactlist feedback
  src/app/(pages)/(nav)/people/page.tsx
  src/components/contacts/ContactList.tsx
Labels: 🦁영진, 🎨 Style

#184 Fix#183 이미지 컴포넌트에 height 속성 추가
  src/components/home/MainHeader.tsx
  src/components/home/SectionOne.tsx
  src/components/home/SectionThree.tsx
  src/components/home/SectionTwoToggle.tsx
Labels: 🧓기리, 🐞 BugFix

#176 Refactor/#174 month move btn prefetching
  src/app/(pages)/(nav)/calendar/page.tsx
  src/app/api/supabase/service.ts
  src/components/calendar/CustomToolbar.tsx
  src/components/calendar/MainCalendar.tsx
  src/components/calendar/MoveMonthButton.tsx
  src/hooks/mutations/useMutateInsertNewPlan.ts
  src/hooks/queries/useGetCalendarPlans.ts
  src/lib/utils/fetchCalendarPlans.ts
Labels: 🍀진채, ♻️ Refactor

#179 Refactor/#177 holiday bar
  src/app/(pages)/(nav)/calendar/page.tsx
  src/app/globals.css
  src/components/calendar/MainCalendar.tsx
  src/hooks/queries/useGetHolidays.ts
  src/lib/utils/calculateNewDate.ts
  src/lib/utils/calendarStyle.ts
  src/types/plans.ts
Labels: 🍀진채, ♻️ Refactor, 🎨 Style

#182 Refactor/#181 calendar side
  src/app/(pages)/(nav)/calendar/page.tsx
  src/app/page.tsx
  src/components/calendar/SelectPlan.tsx
  src/components/contactDetail/editPlanForm/EditPlanForm.tsx
  src/components/schedule/UpcomingPlans.tsx
Labels: 🍀진채, 🎨 Style

#189 Style/#185 add contactlist label input
  src/components/contacts/addContactForm/AddContactForm.tsx
  src/components/contacts/addContactForm/ProfileImageUpload.tsx
  src/hooks/useContactForm.ts
Labels: 🦁영진, 🎨 Style

#186 Style/#167 contact detail
  src/app/api/supabase/service.ts
  src/components/contactDetail/ContactPlansCard.tsx
  src/components/contactDetail/ContactProfile.tsx
  src/components/contactDetail/editPlanForm/EditPlanForm.tsx
  src/components/plans/PriorityField.tsx
  src/hooks/mutations/useMutateEditContact.ts
  src/types/plans.ts
Labels: 🦄시헌, ✨ Feature, 🎨 Style
